### PR TITLE
fix: restructure menu header for styling

### LINKED ISSUE #987: menu header padding and bottom border not customizable
the internal menu header slot element has a padding and border-bottom that can't be changed.

### PR DESCRIPTION
**Pull request by luwes**
fix #987

### CODE REVIEW

File: src/js/menu/media-chrome-menu.ts [hunk 1]
```diff
@@ -141,27 +141,30 @@ template.innerHTML = /*html*/ `
...
       display: inline-flex;
       align-items: center;
+    }
+
+    slot[name="header"][hidden] {
+      display: none;
+    }
+
+    slot[name="header"] > *,
+    slot[name="header"]::slotted(*) {
```
Comment (luwes) [inline src/js/menu/media-chrome-menu.ts:160]: by setting it on the default or slotted elements the styles can be easily overridden

File: src/js/menu/media-chrome-menu.ts [hunk 2]
```diff
@@ -729,7 +733,7 @@ class MediaChromeMenu extends globalThis.HTMLElement {
     return headerSlot
       .assignedElements({ flatten: true })
       ?.find(
-        (el) => el.part.contains('back') && el.part.contains('button')
+        (el) => el.matches('button[part~="back"]')
```
Comment (luwes) [inline src/js/menu/media-chrome-menu.ts:736]: keep consistent with CSS selector (cursor pointer) above

**Review by cjpillsbury — APPROVED** [review]
lgtm
