### PR TITLE
fix: timerange thumb and tooltip drift mobile

### LINKED ISSUE #883: timerange thumb and tooltip drift mobile
the time tooltip and thumb of the time range seem to drift apart if scrubbing on mobile, especially if you hold on and move vertically.

image_from_ios

### PR DESCRIPTION
**Pull request by Pintorado**
Fixes #883 
## Changes
Modified the pointer position calculation in `getPointerRatio`

### CODE REVIEW

File: src/js/utils/element-utils.ts [hunk 1]
```diff
@@ -173,14 +173,20 @@ export function getPointProgressOnLine(
...
+  if (isVertical) {
+    // For vertical lines, calculate progress from bottom to top
+    const totalHeight = p2.y - p1.y;
+    const progress = (y - p1.y) / totalHeight;
+    return Math.max(0, Math.min(1, progress));
+  } else {
+    // For horizontal lines, calculate progress from left to right
+    const totalWidth = p2.x - p1.x;
+    const progress = (x - p1.x) / totalWidth;
+    return Math.max(0, Math.min(1, progress));
```
Comment (luwes) [inline src/js/utils/element-utils.ts:188]: this is a good try but it excludes the very edge case where a slider would be not vertical or horizontal. I asked AI to see what was wrong with the original function and it came back with this. It seems on mobile to fix the issue as well. Could you verify it works with the vertical slider case?

```js
/**
 * Get progress ratio of a point on a line segment.
 * @param x - The x coordinate of the point.
 * @param y - The y coordinate of the point.
 * @param p1 - The first point of the line segment.
 * @param p2 - The second point of the line segment.
 */
export function getPointProgressOnLine(
  x: number,
  y: number,
  p1: Point,
  p2: Point
): number {
  const dx = p2.x - p1.x;
  const dy = p2.y - p1.y;
  const lengthSquared = dx * dx + dy * dy;

  if (lengthSquared === 0) return 0; // Avoid division by zero if p1 === p2

  const projection = ((x - p1.x) * dx + (y - p1.y) * dy) / lengthSquared;

  return Math.max(0, Math.min(1, projection)); // Clamp between 0 and 1
}
```

File: src/js/media-chrome-range.ts [hunk 2]
```diff
@@ -515,13 +515,15 @@ class MediaChromeRange extends globalThis.HTMLElement {
...
+    const startRect = this.#startpoint.getBoundingClientRect();
+    const endRect = this.#endpoint.getBoundingClientRect();
+    
+    return getPointProgressOnLine(
       evt.clientX,
       evt.clientY,
-      this.#startpoint.getBoundingClientRect(),
-      this.#endpoint.getBoundingClientRect()
+      { x: startRect.left, y: startRect.bottom },
+      { x: endRect.left, y: endRect.top }
```
Comment (luwes) [inline src/js/media-chrome-range.ts:525]: this change shouldn't be needed. please revert.

File: src/js/utils/element-utils.ts (hunk 1 above)
Comment (Pintorado) [reply src/js/utils/element-utils.ts:188]: Yes this works, I'll update, thank you

**Review by luwes — APPROVED** [review]
👍 thank you!
