### PR TITLE
fix/range-background: Make sure numeric values are removed as attribu…

### LINKED ISSUE #56: No progress bar background initially
Looks like we lost a background on the main progress bar at some point. It may only happen when preload="none".

image

Compare /examples/standalone-controls.html

image

to https://unpkg.com/media-chrome@0.2.2/examples/standalone-controls.html

image

### PR DESCRIPTION
**Pull request by cjpillsbury**
…tes if/when NaN (instead of set).

* fixes #56

### CODE REVIEW

File: src/js/media-controller.js [hunk 1]
```diff
@@ -444,6 +444,9 @@ const setAttr = (child, attrName, attrValue) => {
     if (attrValue) return child.setAttribute(attrName, '');
     return child.removeAttribute(attrName);
   }
+  if (typeof attrValue === 'number' && Number.isNaN(attrValue)) {
+    return child.removeAttribute(attrName);
+  }
```
Comment (dylanjha) [inline src/js/media-controller.js:449]: Makes sense 👍🏼

**Review by dylanjha — APPROVED** [review]

File: src/js/media-controller.js (hunk 1 above)
Comment (heff) [reply src/js/media-controller.js:449]: If you use `Number.isNaN` the type check is supposed to be not necessary.

**Review by heff — APPROVED** [review]

File: src/js/media-controller.js (hunk 1 above)
Comment (cjpillsbury) [reply src/js/media-controller.js:449]: Yup good callout. Was modeling it on "type" + specific behavior, but it's redundant in this case. Will remove before merging.
