### PR TITLE
fix: fix #299 right click on media element

### LINKED ISSUE #299: Gesture receiver element breaks <video> right click
We shouldn't prevent showing the extra options like loop, PiP, controls, etc. that are shown on a right click on the slotted media element. They are useful and expected by many users.

Smaller reason for devs, right clicking to go straight to the video DOM element in web inspector.

### PR DESCRIPTION
**Pull request by luwes**
prevents the media-gesture-receiver from capturing all the click events. instead the pointer events are attached to window.

still uses the bounding box of the gesture receiver elements to check if the click event was on it or not allowing for potential positioning of other gesture receiver elements.

### CODE REVIEW

File: src/js/media-gesture-receiver.js [hunk 1]
```diff
@@ -54,9 +50,19 @@ class MediaGestureReceiver extends window.HTMLElement {
...
     };
 
-    this.addEventListener('pointerdown', pointerDownHandler);
+    window.addEventListener('pointerdown', pointerDownHandler);
+
+    // Cannot use composedPath or target because this is a layer on top and pointer events are disabled.
+    // Attach to window and check if click is in this element's bounding box to keep <video> right-click menu.
+    window.addEventListener('click', (event) => {
+      const { clientX, clientY } = event;
+      const { left, top, width, height } = this.getBoundingClientRect();
```
Comment (cjpillsbury) [inline src/js/media-gesture-receiver.js:59]: idea: could we instead only `getBoundingClientRect()` on `resize` events to avoid recomputing on any page click?

Comment (gkatsev) [reply src/js/media-gesture-receiver.js:59]: Would this be helpful as an alternative as well? https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint

File: src/js/media-gesture-receiver.js [hunk 2]
```diff
@@ -54,9 +50,19 @@ class MediaGestureReceiver extends window.HTMLElement {
       this._pointerType = e.pointerType;
     };
 
-    this.addEventListener('pointerdown', pointerDownHandler);
+    window.addEventListener('pointerdown', pointerDownHandler);
```
Comment (cjpillsbury) [inline src/js/media-gesture-receiver.js:53]: issue(blocker): let's move the adding of the event handler to `connectedCallback` and add a corresponding remove to `disconnectedCallback` (can add a private method for `pointerDownHandler`)

**Review by cjpillsbury — CHANGES_REQUESTED** [review]
a couple of thoughts, but this is looking like the way we'll have to go to not block right clicks.

File: src/js/media-gesture-receiver.js (hunk 1 above)
Comment (gkatsev) [reply src/js/media-gesture-receiver.js:59]: ah, elementFromPoint might not work due to the point-events:none thing

**Review by cjpillsbury — APPROVED** [review]
😎 awesome.

File: src/js/media-gesture-receiver.js [hunk 3]
```diff
@@ -16,6 +15,12 @@ template.innerHTML = `
 </style>
 `;
 
+const resizeObserver = new ResizeObserver((entries) => {
+  for (const entry of entries) {
+    entry.target.rect = entry.target.getBoundingClientRect();
+  }
+});
```
Comment (luwes) [inline src/js/media-gesture-receiver.js:22]: I saw this a while back 1 resizeobserver vs multiple per element performs a lot better

**Review by gkatsev — APPROVED** [review]
