### PR TITLE
fix: sticky chapter on mouseout

### LINKED ISSUE #999: sticky timeline chapters
Image

they don't go back to normal height sometimes

### PR DESCRIPTION
**Pull request by luwes**
fix #999

I can't reproduce it anymore so hopefully fixed.

the bug happened when `updateSegments` was called multiple times, easier to reproduce with preload none. 
`insertCSSRule` created a rule every time `updateSegments` was called so it possibly happened while the user hovered over a chapter.

### CODE REVIEW

File: src/js/media-chrome-range.ts [hunk 1]
```diff
@@ -388,6 +387,10 @@ class MediaChromeRange extends globalThis.HTMLElement {
     this.#cssRules.pointer = getOrInsertCSSRule(this.shadowRoot, '#pointer');
     this.#cssRules.progress = getOrInsertCSSRule(this.shadowRoot, '#progress');
     this.#cssRules.thumb = getOrInsertCSSRule(this.shadowRoot, '#thumb');
+    this.#cssRules.activeSegment = getOrInsertCSSRule(
```
Comment (cjpillsbury) [inline src/js/media-chrome-range.ts:390]: SMRT.

**Review by cjpillsbury — APPROVED** [review]
Makes sense as a change per earlier out of band convo.
